# Generated by Django 3.2.7 on 2021-09-09 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('CourseType', models.CharField(max_length=8)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CourseApp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_q', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OfflineCourse',
            fields=[
                ('CourseID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='CourseApp.course')),
                ('e_time', models.TimeField()),
                ('b_time', models.TimeField()),
                ('e_date', models.DateField()),
                ('b_date', models.DateField()),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OnlineCourse',
            fields=[
                ('CourseID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='CourseApp.course')),
                ('raters', models.FloatField()),
                ('rating', models.IntegerField()),
                ('type', models.CharField(max_length=30)),
                ('duration', models.CharField(max_length=50)),
                ('lessons_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('segmentID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CourseApp.course')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segmentID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CourseApp.usersegment')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CourseApp.course')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CourseApp.course')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.TextField()),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CourseApp.course')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('choiceID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CourseApp.surveychoice')),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CourseApp.course')),
                ('questionID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CourseApp.surveyquestion')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('ansChoiceID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CourseApp.choice')),
                ('examID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CourseApp.exam')),
            ],
        ),
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=100)),
                ('lessonID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CourseApp.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CourseApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500)),
                ('lessonID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CourseApp.lesson')),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='questionID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CourseApp.question'),
        ),
        migrations.AddField(
            model_name='category',
            name='imgID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CourseApp.image'),
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CourseApp.exam')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CourseApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserJoinsCourseWpayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_unlocked', models.DateTimeField(auto_now_add=True)),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CourseApp.course')),
                ('paymentID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CourseApp.payment')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CourseApp.user')),
            ],
            options={
                'unique_together': {('userID', 'courseID', 'paymentID')},
            },
        ),
        migrations.CreateModel(
            name='UserCommentedOnCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CourseApp.comment')),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CourseApp.course')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CourseApp.user')),
            ],
            options={
                'unique_together': {('userID', 'commentID', 'courseID')},
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='OnlineCourseID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CourseApp.onlinecourse'),
        ),
        migrations.CreateModel(
            name='AttemptSolveQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attemptID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CourseApp.attempt')),
                ('pickedChoiceID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CourseApp.choice')),
                ('questionID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CourseApp.question')),
            ],
            options={
                'unique_together': {('attemptID', 'questionID', 'pickedChoiceID')},
            },
        ),
    ]
