# Generated by Django 3.2.7 on 2021-09-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='raters',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='course',
            name='rating',
            field=models.IntegerField(default=1),
        ),
    ]
