# Generated by Django 3.2.7 on 2021-09-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseApp', '0002_auto_20210916_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
